AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName:
    Description: "Name of the application"
    Type: String
  AppDescription:
      Description: "Name of the application"
      Default: app description...
      Type: String
  SolutionStack:
      Description: name of prebuilt environment provided by aws.
      Type: String
  S3BucketName: 
    Description: "Enter the name of s3 bucket"
    Type: String
  DeploymentPackage: 
    Description: "Enter the path of zip  file relative to s3 bucket"
    Type: String
  MaxInstanceCount: 
    Description: "Enter the maximum number of instance in auto scaling group"
    Default: '2'
    Type: String
  SSLCertRef:
    Description: ARN of Certificate uploaded in ACM.
    Type: String
  DBName:
    Description: name of db instance.
    Type: String
  DBEngine:
    Description: choose from this link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html.
    Default: 'postgres'
    Type: String
  DBEngineVersion:
    Description: database engine version use command aws rds describe-db-engine-versions  --engine postgres.
    Default: '12.7'
    Type: String
  DBLicenseModel:
    Description: choose from this link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html.
    Default: 'postgresql-license'
    Type: String
  DBInstanceSize:
    Description: size of db instance hardware.
    Default: db.t2.small
    Type: String
  DBCapacity:
    Description: Storage in gbs.
    Default: '5'
    Type: String
  DBUserName:
    Description: username of database.
    Type: String
  DBPassword:
    Description: password for the user of database.
    Type: String
  # DBRetensionPolicy:
  #   Description: Retain, Snapshot or Delete.
  #   Default: "Snapshot"
  #   AllowedValues:
  #     - "Snapshot"
  #     - "Retain"
  #     - "Delete"
  #   Type: String


Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ingress on port 5432. 
      SecurityGroupIngress:
        - IpProtocol: -1
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  AppDB:
    Type: AWS::RDS::DBInstance
    DependsOn: DBSecurityGroup
    Properties:
      DBName: !Ref DBName
      DBSecurityGroups:
      - !Ref: DBSecurityGroup
      Engine: 
        Ref: DBEngine
      EngineVersion: 
        Ref: DBEngineVersion
      LicenseModel: 
        Ref: DBLicenseModel
      AllocatedStorage: 
        Ref: DBCapacity
      DBInstanceClass: 
        Ref: DBInstanceSize
      MasterUsername: 
        Ref: DBUserName
      MasterUserPassword: 
        Ref: DBPassword
    DeletionPolicy: Retain  #TODO: make change if required

  djangoApp:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName:
        Ref: AppName
      Description:
        Ref: AppDescription
  AppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: djangoApp
      Description: 
        Ref: AppDescription
      SourceBundle:
        S3Bucket: 
          Ref: S3BucketName
        S3Key:
          Ref: DeploymentPackage
  AppConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    DependsOn: AppDB
    Properties:
      ApplicationName:
        Ref: djangoApp
      Description: Django REST API Configuration Template
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: DB_HOST
        Value: !GetAtt AppDB.Endpoint.Address
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: DB_PORT
        Value: !GetAtt AppDB.Endpoint.Port
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: DB_NAME
        Value: !Ref DBName
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: DB_USER_NAME
        Value: !Ref DBUserName
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: DB_PASSWORD
        Value: !Ref DBPassword
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '6'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref MyInstanceProfile
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elb:listener:443
        OptionName: ListenerProtocol
        Value: HTTPS
      - Namespace: aws:elb:listener:443
        OptionName: InstancePort
        Value: 80
      - Namespace: aws:elb:listener:443
        OptionName: InstanceProtocol
        Value: HTTP
      - Namespace: aws:elb:listener:443
        OptionName: SSLCertificateId
        Value:
          Ref: SSLCertRef       
      SolutionStackName:
        Ref: SolutionStack
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: djangoApp
      Description: AWS ElasticBeanstalk Sample Environment
      TemplateName:
        Ref: AppConfigurationTemplate
      VersionLabel:
        Ref: AppVersion
  MyInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref MyInstanceRole

Outputs:
  EndpointURL:
    Description: the link of deployed application
    Value: !GetAtt Environment.EndpointURL