AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3BucketName: 
    Description: "Enter the name of s3 bucket"
    Type: String


Resources:
  djangoappS3:
    Type: AWS::S3::Bucket
    Properties:
       BucketName: 
        Ref: S3BucketName

# make sure buckentname is in lowercaps & globally unique.